### ISSUE TITLE
HSTSの時間が短い

### ISSUE THREAD

**Issue by otofune** [MissKernel/Misskey-Web#121]
Mozillaが[公開している推奨するHSTS設定](https://wiki.mozilla.org/Security/Server_Side_TLS#HSTS:_HTTP_Strict_Transport_Security)より短く、[SSL Server Test (Powered by QUALYS SSL Labs)](https://www.ssllabs.com/ssltest/)を行うとtoo shortと出る問題。
HSTSの時間を半年以上にすると解決します。(max age=15768000以上)

**Comment by syuilo** [comment]
configで設定できてもいいかもしれませんね。

**Comment by otofune** [comment]
configで設定できるようにするなら、https関連でリバースプロキシ時に内部でhttpsを利用しないという選択肢も追加してみたいなあと

**Comment by syuilo** [comment]
なるほど

**Comment by otofune** [comment]
旧[Misskey-Web](https://github.com/misskeylink/Misskey-Web)だとconfig.jsonで直接URLが指定できたのでhttpsがdisableでもhttps接続させるのに問題はなかったのです、今SSL LabsのSSL Server TestでA+が取得できた[Misskeyミラー](https://misskey.cf)ではmisskey本体はhttpで動作し、nginxにすべてのSSL処理を任せています。
