### ISSUE TITLE
noindex metaタグを設定で付けられるようにする

### ISSUE THREAD

**Issue by rinsuki** [MissKernel/Misskey-Web#123]
```
<meta name="robots" content="noindex,nofollow">
```

これ
contentを設定できるようにしてもいいかもしれない

**Comment by syuilo** [comment]
noindexの必要性がわからない

**Comment by otofune** [comment]
Webのミラー運営時に同じページが検索エンジンに取り込まれた場合、検索した時に重複して出てくるなどの不具合が考えられる

**Comment by syuilo** [comment]
そういう意図だったら canonical とかなかったっけ

**Comment by otofune** [comment]
ミラー運営時の問題はそちらで解決できそう
もうひとつ単純に検索から流入してくることを望んでいない場合の内輪で使うSNSとして使いたい時にnoindexが欲しいと少しばかり思う

**Comment by syuilo** [comment]
検索から流入してくることを望んでいない場合の内輪で使うSNSとして使いたい時がない

**Comment by syuilo** [comment]
Misskeyは、第三者が動かすことを想定しないスタンスです。

**Comment by otofune** [comment]
なるほど、ならばこれは必要ないですね
