### ISSUE TITLE
Notification APIで通知する

### ISSUE THREAD

**Issue by potato4d** [MissKernel/Misskey-Web#135]
現状、効果音での通知及びアクセス中の通知は可能であるが、別タブ/別窓の時に内容を見たい時がある。

Web Push通知でも良いが、需要とコスト、さらにデプロイが面倒になることを考えて、Notification API辺りで実装されると嬉しいなーと。

**Comment by syuilo** [comment]
SWでの実装になりますね

**Comment by potato4d** [comment]
そっちでやるの辛ない論あったからさっと実装したほうで書きましたが、Push Notificationの方（SWの方）で実装できるなら無論そちらのほうがありがたいのでオナシャス
